# Site settings
title: Blog
header-img: img/home-bg.jpg
email: hellfish2@gmail.com
description: "Web + UX/UI + Frontend + Android Developer"
avatar: "https://avatars1.githubusercontent.com/u/2073636?v=3&s=460"
baseurl: ""
url: "http://hellfish2.github.io"
twitter_username: hellfish2
github_username:  hellfish2
facebook_username:  hellfish2
linkedin_username: hellfish2
google_analytics: UA-53211355-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
